// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SweetProduction.proto

package io.siddhi.distribution.sample.grpc;

public interface SweetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sweet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();
}
