/*
 * Copyright (c)  2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.io.grpc.proto;

public interface RequestWithMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestWithMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  boolean containsMap(
          String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getMap();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  java.util.Map<String, String>
  getMapMap();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */

  String getMapOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */

  String getMapOrThrow(
          String key);
}
