// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SweetProduction.proto

package io.siddhi.distribution.sample.grpc;

public final class SweetProduction {
  private SweetProduction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sweet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sweet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025SweetProduction.proto\"$\n\005Sweet\022\014\n\004name" +
      "\030\001 \001(\t\022\r\n\005price\030\002 \001(\0012-\n\014SweetService\022\035\n" +
      "\013getDiscount\022\006.Sweet\032\006.SweetB&\n\"io.siddh" +
      "i.distribution.sample.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Sweet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sweet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sweet_descriptor,
        new String[] { "Name", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
