// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.io.grpc.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>int64 longValue = 3;</code>
   */
  long getLongValue();

  /**
   * <code>bool booleanValue = 4;</code>
   */
  boolean getBooleanValue();

  /**
   * <code>float floatValue = 5;</code>
   */
  float getFloatValue();

  /**
   * <code>double doubleValue = 6;</code>
   */
  double getDoubleValue();
}
