// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package io.siddhi.extension.io.grpc.proto;

public interface ResponseWithMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseWithMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringValue = 1;</code>
   */
  String getStringValue();
  /**
   * <code>string stringValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  boolean containsMap(
          String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getMap();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */
  java.util.Map<String, String>
  getMapMap();
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */

  String getMapOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; map = 3;</code>
   */

  String getMapOrThrow(
          String key);
}
